# Form implementation generated from reading ui file 'c:\Users\Ian\OneDrive - ualberta.ca\Documents\GitHub\Scoreboard\build\exe.win-amd64-3.10\lib\src\editor\complisttab.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_yay(object):
    def setupUi(self, yay):
        yay.setObjectName("yay")
        yay.resize(243, 204)
        self.gridLayout = QtWidgets.QGridLayout(yay)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.treeView = QtWidgets.QTreeView(yay)
        self.treeView.setDragEnabled(True)
        self.treeView.setDragDropMode(QtWidgets.QAbstractItemView.DragDropMode.DragOnly)
        self.treeView.setIconSize(QtCore.QSize(50, 50))
        self.treeView.setIndentation(0)
        self.treeView.setObjectName("treeView")
        self.treeView.header().setVisible(False)
        self.gridLayout.addWidget(self.treeView, 0, 0, 1, 1)

        self.retranslateUi(yay)
        QtCore.QMetaObject.connectSlotsByName(yay)

    def retranslateUi(self, yay):
        _translate = QtCore.QCoreApplication.translate
        yay.setWindowTitle(_translate("yay", "Form"))
